### ISSUE TITLE
javalin json body parse error after upgrading from 1.34 to 1.35 (including 1.41)

### ISSUE THREAD

**Issue by literallyEllie** [avaje/avaje-http#223]
Hello 😄 ,

I just updated one of my projects which was using `avaje-http-javalin-generator` `1.31` to the current, and then happened to send a POST request with a json body and got the following error:

```
[JettyServerThreadPool-30] ERROR io.javalin.Javalin - Fatal error occurred while servicing http-request
kotlin.NotImplementedError: JsonMapper#fromJsonStream not implemented
	at io.javalin.json.JsonMapper.fromJsonStream(JsonMapper.kt:67)
	at io.javalin.http.Context.bodyStreamAsClass(Context.kt:138)
	at live.rehope.site.endpoint.inventory.unlock.UnlockController$Route.lambda$registerRoutes$2(UnlockController$Route.java:43)
```

Endpoint (my impl never gets called):
```java
    @Post
    @EndpointRoles(UserRole.ADMIN)
    public UnlockCode addCode(UnlockCode code) { .. }
```

UnlockCode (but has happens with any body)
```java
public record UnlockCode(int id, String code, int redeemLimit, int uses, boolean active, int unlockElementId)
```

Sent body:
```json
{
    "code": "hello",
    "redeemLimit": -1, 
    "active": true,
    "unlockElementId": 1
}
```

Generated route
```java
    ApiBuilder.post("/api/code", ctx -> {
      ctx.status(201);
      /* error line 43 */ var code = ctx.<live.rehope.site.endpoint.inventory.unlock.UnlockCode>bodyStreamAsClass(live.rehope.site.endpoint.inventory.unlock.UnlockCode.class); 
      var result = controller.addCode(code);
      ctx.json(result);
    }, ADMIN);
```

I'm using GSON as a JSON mapper, and it does work in previous versions.
```java
        config.jsonMapper(new JsonMapper() {
            @NotNull
            @Override
            public <T> T fromJsonString(@NotNull String json, @NotNull Type targetType) {
                return gson.fromJson(json, targetType);
            }

            @NotNull
            @Override
            public String toJsonString(@NotNull Object obj, @NotNull Type type) {
                return gson.toJson(obj, type);
            }
        });
```

Versions:
```
    implementation("io.javalin:javalin:5.5.0")

    // Avaje
    implementation("io.avaje:avaje-config:3.4")
    implementation("io.avaje:avaje-http-api:1.41")
    annotationProcessor("io.avaje:avaje-http-javalin-generator:1.41") // <--- works 1.34, breaks 1.35

    implementation("io.avaje:avaje-inject:9.2")
    annotationProcessor("io.avaje:avaje-inject-generator:9.2")

    implementation("com.google.code.gson:gson:2.10.1")
```

https://github.com/avaje/avaje-http/commit/e8d40cd1182c4f959213dcdf8800fe562c8574c5 https://github.com/avaje/avaje-http/commit/f3fd134c348b9e33e22379102673345de24f4e7e Maybe related?

Much appreciated, and hopefully this isn't just me missing something- but I think not?

**Comment by SentryMan** [comment]
For efficiency's sake, we changed to using streams. You'll need to implement the `JsonMapper#fromJsonStream` method.

**Comment by literallyEllie** [comment]
Ohh I should have noticed this, sorry haha. ok never mind then 😎
