### ISSUE TITLE
[HTTP-Client] 204 deserialization error

### ISSUE THREAD

**Issue by SentryMan** [avaje/avaje-http#426]
[Essentially Copied from discord]

Suppose an api call to a server results in a 204. `.GET().as(MyBean.class)` tries to deserialise the body (of which is empty), resulting in an error during deserialization 

What I would've expected is:
1. Just don't deserialise when it's a 204 or you know the body is empty in the first place.
2. Only deserialise when `.body()` is called. That way it's down to the implementation to know when it should and shouldn't expect a body. So for example, in a 204, I shouldn't call `.body()` but in other scenarios I should probably expect the body to be present.

**Comment by rob-bygrave** [comment]
How does it become a 204?  Does the status code get set by the response or is null returned from a method or something else?  What does the controller code look like for this case?

**Comment by rob-bygrave** [comment]
Oh, this is for **_HttpClient_** .... getting a response status code 204 ... oh.

**Comment by rbygrave** [comment]
Example stack trace:

```
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
    at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1457)
    at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:558)
    at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:378)
    at io.avaje.http.client.gson.GsonBodyAdapter$Reader.read(GsonBodyAdapter.java:111)
    ... 42 more
```
